import streamlit as st
import datetime
from dotenv import load_dotenv
from agent.agentic_workflow import GraphBuilder

load_dotenv()

st.set_page_config(
    page_title="AI Travel Planner",
    page_icon="🌍",
    layout="centered",
    initial_sidebar_state="expanded",
)

st.title("🌍 Marketing Campaign Planner")

# Initialize chat history
if "messages" not in st.session_state:
    st.session_state.messages = []

# Display chat history
st.header("How can I help you in planning a trip? Let me know where do you want to visit.")

# Chat input box at bottom
with st.form(key="query_form", clear_on_submit=True):
    user_input = st.text_input("User Input", placeholder="e.g. Plan a trip to Goa for 5 days")
    submit_button = st.form_submit_button("Send")

if submit_button and user_input.strip():
    try:
        # Show thinking spinner while backend processes
        with st.spinner("Bot is thinking..."):
            agent = GraphBuilder(model_provider="groq")()
            output = agent.invoke({"messages": [user_input]})
            answer = output["messages"][-1].content

        import textwrap
        markdown_content = textwrap.dedent(f"""\
            # 🌍 Travel Plan

            # **Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}  
            # **Created by:** Manish's Travel Agent

            ---

            {answer}

            ---

            *This travel plan was generated by AI. Please verify all information before your trip.*
            """)
        st.markdown(markdown_content)
    except Exception as e:
        st.error(f"Error: {e}")

