import os
import datetime

def save_document(response_text: str, directory: str = "./output") -> str:
    """Export travel plan to Markdown file."""
    os.makedirs(directory, exist_ok=True)
    
    markdown_content = f"""# 🌍 AI Travel Plan

**Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}
**Created by:** Atriyo's Travel Agent

---

{response_text}

---

*This travel plan was generated by AI. Please verify all information before your trip.*"""
            
    try:
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        filename = f"{directory}/AI_Trip_Planner_{timestamp}.md"
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(markdown_content)
        return filename
    except Exception as e:
        print(f"Error saving markdown file: {e}")
        return None